In [1]:
import numpy as py

In [19]:
num=py.array([23,42,54,65,76,55])

In [20]:
print(num)

[23 42 54 65 76 55]


In [33]:
num.shape      #x and Y in multi-D form

(6,)

In [34]:
num=py.array([23,42,54,65.65,76,55])

In [35]:
print(num)

[23.   42.   54.   65.65 76.   55.  ]


In [37]:
type(num)

numpy.ndarray

In [57]:
chr(95)        #to find the element in the ASCII code num

'_'

In [24]:
ord('a')       #to find the char code

97

In [25]:
ord("E")

69

In [27]:
ord("A")

65

In [28]:
city=['पुणे',' पुने',' मुंबई ','मुम्बई']

In [29]:
city[1]

' पुने'

In [30]:
city[0]*5

'पुणेपुणेपुणेपुणेपुणे'

In [31]:
### Array

In [32]:
city[0].startswith('पु')

True

In [48]:
num=py.array([23,42,54,65,76,55])     #ARRAY
x=[23,42,54,65,76,55]                 #LIST

In [43]:
###### LIST

In [39]:
x*2

[23, 42, 54, 65, 76, 55, 23, 42, 54, 65, 76, 55]

In [41]:
### array

In [40]:
num*2

array([ 46,  84, 108, 130, 152, 110])

In [44]:
num+2

array([25, 44, 56, 67, 78, 57])

In [47]:
num-60

array([-37, -18,  -6,   5,  16,  -5])

In [51]:
num>60

array([False, False, False,  True,  True, False])

In [52]:
54 in num

True

In [53]:
54 in x

True

In [54]:
45 not in num

True

In [55]:
54 not in x

False

In [60]:
py.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
py.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
py.empty(8)

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 5.96831300e-321, 1.42419937e-306, 7.56603880e-307])

In [63]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [68]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [69]:
list(range(2,15,3))

[2, 5, 8, 11, 14]

In [70]:
list(range(20,2-2))

[]

In [71]:
py.arange(10)       #ARRAY RANGE

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
py.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [73]:
py.arange(1,10,0.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])

In [74]:
py.arange(10,0,-1.5)

array([10. ,  8.5,  7. ,  5.5,  4. ,  2.5,  1. ])

In [78]:
num

array([23, 42, 54, 65, 76, 55])

In [75]:
num.max()

76

In [76]:
num.mean()

52.5

In [77]:
num.argmax()

4

In [79]:
py.linspace(1,10,12)        #linearly Spaced 10 elements 1 to 12 mean Diff b/w two is same

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [84]:
py.linspace(1,5,22)  

array([1.        , 1.19047619, 1.38095238, 1.57142857, 1.76190476,
       1.95238095, 2.14285714, 2.33333333, 2.52380952, 2.71428571,
       2.9047619 , 3.0952381 , 3.28571429, 3.47619048, 3.66666667,
       3.85714286, 4.04761905, 4.23809524, 4.42857143, 4.61904762,
       4.80952381, 5.        ])

In [81]:
py.linspace(1,10,4)  

array([ 1.,  4.,  7., 10.])

#metrix is collection of array of equal length

In [151]:
x=py.array([[1,2,0,3],[4,10,5,6],[7,11,8,9]])

In [93]:
x

array([[ 1,  2,  0,  3],
       [ 4, 10,  5,  6],
       [ 7, 11,  8,  9]])

In [97]:
x.shape

(3, 4)

In [98]:
x.size

12

In [91]:
x[2][1]

8

In [94]:
x.reshape(4,3)

array([[ 1,  2,  0],
       [ 3,  4, 10],
       [ 5,  6,  7],
       [11,  8,  9]])

In [95]:
x.reshape(2,6)

array([[ 1,  2,  0,  3,  4, 10],
       [ 5,  6,  7, 11,  8,  9]])

In [96]:
x.reshape(6,2)

array([[ 1,  2],
       [ 0,  3],
       [ 4, 10],
       [ 5,  6],
       [ 7, 11],
       [ 8,  9]])

In [99]:
x.reshape(4,-1)

array([[ 1,  2,  0],
       [ 3,  4, 10],
       [ 5,  6,  7],
       [11,  8,  9]])

In [100]:
x.reshape(3,-1)

array([[ 1,  2,  0,  3],
       [ 4, 10,  5,  6],
       [ 7, 11,  8,  9]])

In [107]:
x.reshape(1,-1)      #negative values means adjust accordingly to the +ve value

array([[ 1,  2,  0,  3,  4, 10,  5,  6,  7, 11,  8,  9]])

In [108]:
x.flatten()         #to convert in vector form mean in 1-D

array([ 1,  2,  0,  3,  4, 10,  5,  6,  7, 11,  8,  9])

In [109]:
x

array([[ 1,  2,  0,  3],
       [ 4, 10,  5,  6],
       [ 7, 11,  8,  9]])

### PANDAS DS

#Series: 1-D Array of same Homogenous Type

#Series is Class

import pandas as pd

In [113]:
s=pd.Series([12,25,65,34,84,72,59])

In [114]:
s

0    12
1    25
2    65
3    34
4    84
5    72
6    59
dtype: int64

In [118]:
type(s)

pandas.core.series.Series

In [119]:
s.dtype

dtype('int64')

In [120]:
s.size

7

In [122]:
s=pd.Series([12,25,65,34,84,72,59],index=range(100,107))

In [123]:
s

100    12
101    25
102    65
103    34
104    84
105    72
106    59
dtype: int64

In [124]:
s[104]

84

### DataFrame Operations

In [128]:
x=pd.Series([1,2,3,4,5])

In [129]:
y=pd.Series(['AAA','BBB','CCC','DDD','EEE'])

In [133]:
z=pd.Series([52,85,65,74,71])

In [134]:
df=pd.DataFrame({
    'roll_no':x,
    'Name':y,
    'marks':z
})

In [135]:
df

roll_no Name  marks
0        1  AAA     52
1        2  BBB     85
2        3  CCC     65
3        4  DDD     74
4        5  EEE     71

In [136]:
df.shape

(5, 3)

In [137]:
df.size

15

In [138]:
df.ndim

2

In [139]:
df.columns

Index(['roll_no', 'Name', 'marks'], dtype='object')

In [140]:
df.T

0    1    2    3    4
roll_no    1    2    3    4    5
Name     AAA  BBB  CCC  DDD  EEE
marks     52   85   65   74   71

### Staticstical INTERFACE